version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "angular-spa/dist"
phases:
  install:
    runtime-versions:
      nodejs: 16.13
    commands:
      - echo installing dependencies...
      - npm install
      - npm i -g @angular/cli
  build:
    commands:
      - echo Build phase starting...
      - ng build
artifacts:
  files:
    - "**/*"
  base-directory: "angular-spa/dist*"
  discard-paths: yes
